// apps/react/src/components/app-bar/index.tsx
import { Link } from 'react-router-dom';
import Logo from '@assets/images/logo.png';

const AppBar = () => {
    return (
        <header className="flex bg-blue-50 h-16 border-b items-center">
            <div className="px-6">
                <Link to="/" className="inline-block">
                    <img src={Logo} alt="logo" className="w-10 h-10" />
                </Link>
            </div>
            <div className="text-gray-900 text-lg">{import.meta.env.VITE_APP_TITLE}</div>
        </header>
    );
};

export default AppBar;

// apps/vue/src/components/app-bar.vue
<script setup lang="ts">
import logo from '@assets/images/logo.png';

const appTitle = import.meta.env.VITE_APP_TITLE;
</script>

<template>
    <v-app-bar flat color="app-bar-background" class="app-bar">
        <v-app-bar-nav-icon>
            <router-link to="/" class="app-bar-logo"><v-img :width="28" :src="logo"></v-img></router-link>
        </v-app-bar-nav-icon>
        <v-app-bar-title class="app-bar-title">{{ appTitle }}</v-app-bar-title>
    </v-app-bar>
</template>

<style scoped>
.app-bar {
    border-bottom: 2px solid #dee7f6;
}

.app-bar-title {
    color: #326485;
    font-size: 1.125rem;
}
</style>
